services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: userlibrarydb
      POSTGRES_USER: kraken
      POSTGRES_PASSWORD: 1357Kraken1357
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: UserLibraryBackEndApi/Dockerfile
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=userlibrarydb;Username=kraken;Password=1357Kraken1357
      - Jwt__Key=2V8u7uZBKmJtFxS9rM4nLwYc6eR2p9Xa
      - Jwt__Issuer=http://localhost
      - Jwt__Audience=http://localhost
      - Redis__Connection=redis:6379
      - GoogleBooks__ApiKey=AIzaSyB6iqwKxrPx_Jxr2xw1QSk86u_RH6xAMM0
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:80"
    volumes:
      - ./UserLibraryBackEndApi/wwwroot/covers:/app/wwwroot/covers
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: userlibrary-frontend/Dockerfile.prod   # siempre usas el de prod
    ports:
      - "3000:80"   # el frontend queda expuesto en http://localhost
    depends_on:
      - backend   # espera a que el backend est√© levantado

volumes:
  postgres_data: