services:
  userlibrary-postgres:
    image: postgres:15
    container_name: userlibrary-postgres
    restart: always
    environment:
      POSTGRES_DB: UserLibraryDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kraken13
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - userlibrary-net

  userlibrary-redis:
    image: redis:latest
    container_name: userlibrary-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - userlibrary-net

  userlibrary-backend:
    build:
      context: .
      dockerfile: UserLibraryBackEndApi/Dockerfile
    container_name: userlibrary-backend-local
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - "8080:80"
    depends_on:
      - userlibrary-postgres
      - userlibrary-redis
    networks:
      - userlibrary-net

volumes:
  postgres_data:

networks:
  userlibrary-net:
    driver: bridge
